# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_top.xdc

# IP: ip/eth_xcvr_gth_full/eth_xcvr_gth_full.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth_xcvr_gth_full || ORIG_REF_NAME==eth_xcvr_gth_full} -quiet] -quiet
