# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku035-fbva676-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.cache/wt [current_project]
set_property parent.project_path /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_wrapper_functions.v
set_property file_type "Verilog Header" [get_files /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_wrapper_functions.v]
read_verilog -library xil_defaultlib {
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_phy_10g.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_phy_10g_rx.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_phy_10g_rx_ber_mon.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_phy_10g_rx_frame_sync.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_phy_10g_rx_if.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_phy_10g_rx_watchdog.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_phy_10g_tx.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_phy_10g_tx_if.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_bit_sync.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_gtwiz_reset.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_init.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_reset_inv_sync.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_reset_sync.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_wrapper.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/lfsr.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/sync_reset.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/xgmii_baser_dec_64.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/xgmii_baser_enc_64.v
  /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_top.v
}
read_ip -quiet /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/eth_xcvr_gth_full/eth_xcvr_gth_full.xci
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/eth_xcvr_gth_full/synth/eth_xcvr_gth_full_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/eth_xcvr_gth_full/synth/eth_xcvr_gth_full.xdc]

read_ip -quiet /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_gt_debug/ila_gt_debug.xci
set_property used_in_synthesis false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_gt_debug/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_gt_debug/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_gt_debug/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_gt_debug/ila_gt_debug_ooc.xdc]

read_ip -quiet /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_xgmii_rx/ila_xgmii_rx.xci
set_property used_in_synthesis false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_xgmii_rx/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_xgmii_rx/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_xgmii_rx/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/eth_xcvr_gth_full_ex.srcs/sources_1/ip/ila_xgmii_rx/ila_xgmii_rx_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_top.xdc
set_property used_in_implementation false [get_files /home/chenxun/Documents/Project/Venturi/Vivado_example/eth_xcvr_gth_full_ex/imports/eth_xcvr_gth_full_example_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top eth_xcvr_gth_full_example_top -part xcku035-fbva676-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef eth_xcvr_gth_full_example_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file eth_xcvr_gth_full_example_top_utilization_synth.rpt -pb eth_xcvr_gth_full_example_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
