site_name: Venturi Docs

theme:
  name: material
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - FPGA:
      - Overview: FPGA/overview.md
      - MAC_layer_rx: FPGA/MAC_layer_rx.md
      - order_book_parser: FPGA/order_book_parser.md
      - order_book_builder:
          - Overview: FPGA/order_book_builder/overview.md
          - symbol_book: 
            - Overview: FPGA/order_book_builder/symbol_book/overview.md
            - fifo: FPGA/order_book_builder/symbol_book/fifo.md
            - book_builder: 
              - Overview: FPGA/order_book_builder/symbol_book/book_builder/overview.md
              - bram: FPGA/order_book_builder/symbol_book/book_builder/bram.md
            - qty_book_wrapper: 
              - Overview: FPGA/order_book_builder/symbol_book/qty_book_wrapper/overview.md
              - qty_builder: FPGA/order_book_builder/symbol_book/qty_book_wrapper/qty_builder.md
              - tree_builder: FPGA/order_book_builder/symbol_book/qty_book_wrapper/tree_builder.md
              - aligner: FPGA/order_book_builder/symbol_book/qty_book_wrapper/aligner.md
              - bram_dp: FPGA/order_book_builder/symbol_book/qty_book_wrapper/bram_dp.md
      - async_fifo: FPGA/async_fifo.md
      - rx_dma_stage: FPGA/rx_dma_stage.md
      - pcie_wrapper: 
          - Overview: FPGA/pcie_wrapper/overview.md
          - CC_formatter: FPGA/pcie_wrapper/CC_formatter.md
          - CQ_parser: FPGA/pcie_wrapper/CQ_parser.md
          - RC_parser:
            - Overview: FPGA/pcie_wrapper/RC_parser/overview.md
            - RC_gearbox256: FPGA/pcie_wrapper/RC_parser/RC_gearbox256.md
          - RQ_formatter: 
            - Overview: FPGA/pcie_wrapper/RQ_formatter/overview.md
            - RQ_gearbox256: FPGA/pcie_wrapper/RQ_formatter/RQ_gearbox256.md
  - C++:
      - Overview: cpp/overview.md
      - Parser: cpp/parser.md
      - Order Book: cpp/order_book.md
      - Testing: cpp/testing.md
